// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_7g229KdgfQvOIs85p7EOAygYpmOlRCY',
    appId: '1:791515579452:android:05cfa5483c36e8b6d8af39',
    messagingSenderId: '791515579452',
    projectId: 'my-project-0208',
    databaseURL: 'https://my-project-0208.firebaseio.com',
    storageBucket: 'my-project-0208.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8rK2EqwLF3gq5SvPlYG19qs9Y4hC1dj4',
    appId: '1:791515579452:ios:ce4b0e1c3ceefc09d8af39',
    messagingSenderId: '791515579452',
    projectId: 'my-project-0208',
    databaseURL: 'https://my-project-0208.firebaseio.com',
    storageBucket: 'my-project-0208.appspot.com',
    androidClientId: '791515579452-1kl1flt58p3t0gm3ph6m1j4am9rmpjnt.apps.googleusercontent.com',
    iosClientId: '791515579452-dmsunrs2pb9pmunn02geic6o42h9d9m7.apps.googleusercontent.com',
    iosBundleId: 'com.push.exam',
  );
}
